export const SAMPLE_CANDIDATES_DATA = {
  "1741514509821": {
    name: "James Smith",
    position: "Junior Frontend Developer",
    email: "james.smith@example.com",
    city: "Warsaw",
    repo: "https://github.com/jsmith/frontend-projects",
    phone: "+48 501 234 567",
    notes:
      "Candidate with 3 years of React experience. Very good knowledge of TypeScript. Looking for remote work.",
    language: "language_b2",
    rating: "rating_4",
    step: "step_2",
    technologies: {
      javascript: true,
      typescript: true,
      react: true,
      vue: false,
      angular: false,
    },
    color: "#5E35B1",
    id: 1741514509821,
  },
  "1741514509822": {
    name: "Emily Johnson",
    position: "Senior Frontend Developer",
    email: "emily.johnson@example.com",
    city: "Krakow",
    repo: "https://github.com/ejohnson/frontend-solutions",
    phone: "+48 602 345 678",
    notes:
      "7 years of web development experience. Expert in React and Redux. Worked on large-scale e-commerce projects.",
    language: "language_c1",
    rating: "rating_5",
    step: "step_1",
    technologies: {
      javascript: true,
      typescript: true,
      react: true,
      vue: false,
      angular: true,
    },
    color: "#43A047",
    id: 1741514509822,
  },
  "1741514509823": {
    name: "Peter Williams",
    position: "Mid Frontend Developer",
    email: "peter.williams@example.com",
    city: "Wroclaw",
    repo: "https://github.com/pwilliams/ui-components",
    phone: "+48 703 456 789",
    notes:
      "4 years experience with Vue.js. Strong CSS skills. Interested in performance optimization and animation.",
    language: "language_b2",
    rating: "rating_4",
    step: "step_1",
    technologies: {
      javascript: true,
      typescript: true,
      react: false,
      vue: true,
      angular: false,
    },
    color: "#1E88E5",
    id: 1741514509823,
  },
  "1741514509824": {
    name: "Martha Davis",
    position: "Junior Frontend Developer",
    email: "martha.davis@example.com",
    city: "Gdansk",
    repo: "https://github.com/mdavis/frontend-portfolio",
    phone: "+48 804 567 890",
    notes:
      "Recent bootcamp graduate. Passionate about accessibility. Looking for mentorship opportunities.",
    language: "language_b1",
    rating: "rating_3",
    step: "step_1",
    technologies: {
      javascript: true,
      typescript: false,
      react: true,
      vue: false,
      angular: false,
    },
    color: "#FB8C00",
    id: 1741514509824,
  },
  "1741514509825": {
    name: "Thomas Wilson",
    position: "Senior Frontend Developer",
    email: "thomas.wilson@example.com",
    city: "Poznan",
    repo: "https://github.com/twilson/frontend-architecture",
    phone: "+48 905 678 901",
    notes:
      "10+ years in frontend. Angular expert. Experience with design systems and micro-frontends.",
    language: "language_c2",
    rating: "rating_5",
    step: "step_3",
    technologies: {
      javascript: true,
      typescript: true,
      react: false,
      vue: false,
      angular: true,
    },
    color: "#D81B60",
    id: 1741514509825,
  },
  "1741514509826": {
    name: "Caroline Brown",
    position: "Mid Frontend Developer",
    email: "caroline.brown@example.com",
    city: "Warsaw",
    repo: "https://github.com/cbrown/responsive-websites",
    phone: "+48 106 789 012",
    notes:
      "5 years experience. Specialized in CSS animations and responsive design. Looking for product companies.",
    language: "language_b2",
    rating: "rating_4",
    step: "step_2",
    technologies: {
      javascript: true,
      typescript: false,
      react: true,
      vue: true,
      angular: false,
    },
    color: "#00897B",
    id: 1741514509826,
  },
  "1741514509827": {
    name: "Michael Taylor",
    position: "Lead Frontend Developer",
    email: "michael.taylor@example.com",
    city: "Lodz",
    repo: "https://github.com/mtaylor/state-management",
    phone: "+48 207 890 123",
    notes:
      "8 years of React experience. Created custom state management library. Open to team lead roles.",
    language: "language_c1",
    rating: "rating_5",
    step: "step_3",
    technologies: {
      javascript: true,
      typescript: true,
      react: true,
      vue: false,
      angular: false,
    },
    color: "#8E24AA",
    id: 1741514509827,
  },
  "1741514509828": {
    name: "Natalie Green",
    position: "Junior Frontend Developer",
    email: "natalie.green@example.com",
    city: "Szczecin",
    repo: "https://github.com/ngreen/web-projects",
    phone: "+48 308 901 234",
    notes:
      "1 year commercial experience. Background in graphic design. Strong eye for UI details.",
    language: "language_a2",
    rating: "rating_3",
    step: "step_1",
    technologies: {
      javascript: true,
      typescript: false,
      react: true,
      vue: false,
      angular: false,
    },
    color: "#F4511E",
    id: 1741514509828,
  },
  "1741514509829": {
    name: "Adam Roberts",
    position: "Senior Frontend Developer",
    email: "adam.roberts@example.com",
    city: "Krakow",
    repo: "https://github.com/aroberts/frontend-tooling",
    phone: "+48 409 012 345",
    notes:
      "9 years of experience. Vue.js core contributor. Expert in build optimization and frontend testing.",
    language: "language_c1",
    rating: "rating_5",
    step: "step_2",
    technologies: {
      javascript: true,
      typescript: true,
      react: false,
      vue: true,
      angular: false,
    },
    color: "#546E7A",
    id: 1741514509829,
  },
  "1741514509830": {
    name: "Jennifer Miller",
    position: "Mid Frontend Developer",
    email: "jennifer.miller@example.com",
    city: "Warsaw",
    repo: "https://github.com/jmiller/frontend-experiments",
    phone: "+48 510 123 456",
    notes:
      "3 years with Angular. Previously worked in fintech. Interested in WebGL and interactive visualizations.",
    language: "language_b2",
    rating: "rating_4",
    step: "step_2",
    technologies: {
      javascript: true,
      typescript: true,
      react: false,
      vue: false,
      angular: true,
    },
    color: "#00ACC1",
    id: 1741514509830,
  },
};

export const SAMPLE_NOTES_DATA =
  "Frontend Recruitment Notes - Q1 2025\n\nReact candidates showing stronger TypeScript proficiency overall.\n\nVue.js specialists in short supply - consider raising offered salary range.\n\nAngular developers typically requesting higher compensation than budgeted.\n\nTechnical assessment completion rate: 78%\n\nJunior candidates often lacking practical experience with state management.\n\nEnglish proficiency varies significantly - implement standardized language testing.\n\nConsider implementing pair programming sessions in stage 2 interviews.\n\nMost promising candidates showing interest in remote work options.\n\nSenior-level talent pipeline weaker than expected this quarter.\n\nNeed to improve our technical assessment for React candidates - current test too basic.\n\nSeveral candidates with strong portfolios but weak communication skills.\n\nGitHub/GitLab code review should be mandatory before final interview stage.";
